/*
 * Generated by Bluespec Compiler (build 9f4a447)
 * 
 * On Sun Jun 14 10:56:31 IST 2020
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkbarrel32tb.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkbarrel32tb::MODEL_mkbarrel32tb()
{
  mkbarrel32tb_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkbarrel32tb()
{
  MODEL_mkbarrel32tb *model = new MODEL_mkbarrel32tb();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkbarrel32tb &INST_top = *((MOD_mkbarrel32tb *)(instance_ptr));
	 tUInt32 DEF_INST_top_DEF__read__h49;
	 DEF_INST_top_DEF__read__h49 = INST_top.INST_state.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_go = DEF_INST_top_DEF__read__h49 == 0u;
	 INST_top.DEF_WILL_FIRE_RL_go = INST_top.DEF_CAN_FIRE_RL_go;
	 if (INST_top.DEF_WILL_FIRE_RL_go)
	   INST_top.RL_go();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_state.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkbarrel32tb::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkbarrel32tb_instance = new MOD_mkbarrel32tb(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkbarrel32tb_instance->set_clk_0)("CLK");
}
void MODEL_mkbarrel32tb::destroy_model()
{
  delete mkbarrel32tb_instance;
  mkbarrel32tb_instance = NULL;
}
void MODEL_mkbarrel32tb::reset_model(bool asserted)
{
  (mkbarrel32tb_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkbarrel32tb::get_instance()
{
  return mkbarrel32tb_instance;
}

/* Fill in version numbers */
void MODEL_mkbarrel32tb::get_version(unsigned int *year,
				     unsigned int *month,
				     char const **annotation,
				     char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "9f4a447";
}

/* Get the model creation time */
time_t MODEL_mkbarrel32tb::get_creation_time()
{
  
  /* Sun Jun 14 05:26:31 UTC 2020 */
  return 1592112391llu;
}

/* State dumping function */
void MODEL_mkbarrel32tb::dump_state()
{
  (mkbarrel32tb_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkbarrel32tb & mkbarrel32tb_backing(tSimStateHdl simHdl)
{
  static MOD_mkbarrel32tb *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkbarrel32tb(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkbarrel32tb::dump_VCD_defs()
{
  (mkbarrel32tb_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkbarrel32tb::dump_VCD(tVCDDumpType dt)
{
  (mkbarrel32tb_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkbarrel32tb_backing(sim_hdl));
}
